#!/bin/sh
# $Id$
# ###########################################################################
#             Thomas Dreibholz's R Simulation Scripts Collection
#                  Copyright (C) 2005-2008 Thomas Dreibholz
#
#           Author: Thomas Dreibholz, dreibh@exp-math.uni-essen.de
# ###########################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: get-neds [NED Directory] {NED file} ..."
   exit 1
fi

NEDDIR=$1
shift

# ====== Prepare NED directory ==============================================
if [ -e $NEDDIR ] ; then
   rm -rf $NEDDIR
fi
mkdir $NEDDIR || exit 1


# ====== Copy NED files =====================================================
# Create list of NEDs first; otherwise, "find" would also find newly copied
# files in the output directory!
NEDLIST=""
while [ $# -gt 0 ] ; do
   NED=$1
   shift

   if [ -d $NED ] ; then
      NEDLIST="$NEDLIST `find $NED -name "*.ned"`"
   else
      NEDLIST="$NEDLIST $NED"
   fi
done
NEDLIST="`echo $NEDLIST | sort -u`"

if [ "$NEDLIST" != "" ] ; then
   echo $NEDLIST | xargs -n1
   cp $NEDLIST $NEDDIR
else
   echo "--- No .ned files there ---"
fi
