#!/bin/bash
# $Id$
# ###########################################################################
#             Thomas Dreibholz's R Simulation Scripts Collection
#                  Copyright (C) 2005-2010 Thomas Dreibholz
#
#               Author: Thomas Dreibholz, dreibh@iem.uni-due.de
# ###########################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

if [ $# -lt 1 ] ; then
   echo "Usage: package-simproctc [version]" >&2
   exit 1
fi
VERSION=$1


if [ -e simproctc-$VERSION ] ; then
   rm -rf simproctc-$VERSION
fi

svn co https://132.252.152.132/svn/omnetpp/trunk/simproctc simproctc-$VERSION && \
cd simproctc-$VERSION/demo && \
./make-links && \
cd .. && \
rm -f package-simproctc && \
cd .. && \
find simproctc-$VERSION -name ".svn" | xargs rm -rf && \
tar czvf simproctc-$VERSION.tar.gz simproctc-$VERSION
