#!/bin/sh -eu

make extractvectors

./extractvectors test4.vec.bz2 test4-all
./extractvectors test4.vec.bz2 test4-selected 'Throughput of Association'
./extractvectors test4.vec.bz2 test4-selected-with-split '!Throughput of Association'
