#!/bin/sh

make combinesummaries && \
( echo "--values=ALPHA" && echo "--input=input.data.bz2" && \
  echo "--values=BETA"  && echo "--input=input.data" ) | \
./combinesummaries combined.data.bz2 MySceanrio
# G_SLICE=always-malloc valgrind  -v --tool=memcheck --leak-check=yes --show-reachable=no --leak-resolution=high --num-callers=40 --freelist-vol=4000000 ./combinesummaries combined.data.bz2 MySceanrio
