#!/bin/sh

for file in make-environment perform-run get-libs ssrun ssdistribute plotter.R hashfunctions.R simulation.R tools ; do
   if [ -e $file ] ; then
      rm -f $file
   fi
   ln -s ../$file .
done
